### ISSUE TITLE
Some species fail to bind to the tree

### ISSUE THREAD

**Issue by duc-anhle** [jinyizju/U.PhyloMaker#5]
Dear Prof. Jin,

Thank you for creating the universe of Phylomaker. It is such an amazing work!
I am having an issue when creating a tree for my species list. Somehow, some species are fail to bind to the tree. I did check the input format and I am not sure what's wrong. This issue is also described here: https://github.com/jinyizju/V.PhyloMaker/issues/15

Perhaps, could you take a look at this issue?

Best regards,
Anh

**Comment by jinyizju** [comment]
> Dear Prof. Jin,
> 
> Thank you for creating the universe of Phylomaker. It is such an amazing work! I am having an issue when creating a tree for my species list. Somehow, some species are fail to bind to the tree. I did check the input format and I am not sure what's wrong. This issue is also described here: [jinyizju/V.PhyloMaker#15](https://github.com/jinyizju/V.PhyloMaker/issues/15)
> 
> Perhaps, could you take a look at this issue?
> 
> Best regards, Anh

Dear Anh,

Thanks for using the packages. With respect to the issue you raise, I need more information, e.g. your species list and codes, before I can speculate on it.

Best,

Yi

**Comment by duc-anhle** [comment]
Hi Prof. Jin,

I would like to pin the data. Let's say I am working on spider phylogeny. The backbone I am using comes from another study (Fernandez et al., 2018) that resolves the family-level phylogenetic relationships. Most of species in my list are morpho-species.

**raw_backbone:** 
[raw_fernandez_backbone.txt](https://github.com/user-attachments/files/17362259/raw_fernandez_backbone.txt)

**user-modified_backbone:** 
[fernandez_backbone.txt](https://github.com/user-attachments/files/17362217/fernandez_backbone.txt)

**sp.list:** 
[test.csv](https://github.com/user-attachments/files/17361308/test.csv)

## Code to create user-modified_backbone
```
# Function 1:
new_tip_tbl <- function(tree) {
  tree |>
    as_tibble() |>
    filter(label != "NA" & label != "") |>
    mutate(
      new_label = str_replace_all(label, "_", " "),
      new_label = str_remove_all(new_label, " cf"),
      Family_v0 = case_when(
        str_detect(new_label, "dae") ~ str_extract(new_label, "[^ ]+"),
        TRUE ~ ""
      ),
      genus0 = word(new_label, 2),
      col0 = case_when(!str_detect(new_label, "dae") ~ str_extract(new_label, "[^ ]+"), TRUE ~ ""),
      col0 = str_replace_all(col0, "([A-Z])", " \\1"),
      genus1 = word(col0, 2),
      final_genus_v0 = case_when(
        !is.na(genus0) ~ genus0,
        TRUE ~ genus1),
      new_tip = case_when(
        str_detect(col0, " ") ~ col0,
        TRUE ~ label
      )) |> 
    mutate(across(where(is.character), str_trim)) |> 
    mutate(new_tip = str_replace_all(new_tip, " ", "_")) |> 
    select(parent, node, branch.length, new_tip, final_genus_v0) |> 
    separate(
      new_tip,
      sep = "_",
      into = c("col1", "col2", "col3", "col4", "col5", "col6", "col7")
    ) |> 
    mutate_at(c("col4", "col5", "col6", "col7"), ~ str_replace_na(., "")) |> 
    mutate(new_tip = case_when(
      str_detect(col2, "cf") ~ paste(final_genus_v0, col4, col5, col6, col7, sep = " "),
      is.na(col3) & !is.na(col2) ~ paste(final_genus_v0, col2))) |> 
    mutate(col3 = case_when(!is.na(col3) ~ col3, is.na(col3) & is.na(col2) ~ "sp.xx")) |> 
    mutate(new_tip = case_when(
      !is.na(new_tip) ~ new_tip,
      is.na(final_genus_v0) ~ paste(col1, col3, sep = " "),
      TRUE ~ paste(final_genus_v0, col3, col4, col5, col6, col7, sep = " "))) |> 
    mutate(across(where(is.character), str_trim)) |>
    mutate(new_tip = str_replace_all(new_tip, " ", "_"))  
}

# Function 2
spider_label_update <- function(tree) {
  tree |>
    as_tibble() |>
    left_join(new_tip_tbl(tree), join_by("parent", "node", "branch.length")) |>
    mutate(label = coalesce(new_tip, label)) |> 
    mutate(label = str_replace(label, "\\?", "")) |> 
    select(parent, node, branch.length, label) |>
    as.phylo()
}
user_modified_backbone <- spider_label_update(raw_backbone)
```
### Run Phylo.maker

```
gen.list <- sp.list |> 
  distinct(genus, family)

result <- phylo.maker(sp.list, backbone, gen.list, nodes.type = 1, scenario = 3)
```
I got this messages:

```
[1] "Note: 15 species fail to be binded to the tree."
 [1] "Alistra_sp.01"           "Hygropoda_sp.01"         "Micromerys_sp.01"        "Thaumasia_sp.01"         "Hygropoda_sp.02"         "Oedignatha_scrobiculata"
 [7] "Ablemma_sp.01"           "Anapistula_sp.01"        "Brignoliella_sp.01"      "Crassignatha_sp.01"      "Nasoona_sp.01"           "Ablemma_sp.02"          
[13] "Ablemma_sp.03"           "Ablemma_singalang"       "Nescina_sp.01"          
Warning messages:
1: Setting row names on a tibble is deprecated. 
2: Setting row names on a tibble is deprecated. 
3: Setting row names on a tibble is deprecated. 
```
These morpho species - their genera are not included in the backbone, but I think that would not be the problem. 
I am wondering whether I do need to provide a node info table.

Thank you so much for supporting!
Best,
Anh

**Comment by jinyizju** [comment]
> Hi Prof. Jin,
> 
> I would like to pin the data. Let's say I am working on spider phylogeny. The backbone I am using comes from another study (Fernandez et al., 2018) that resolves the family-level phylogenetic relationships. Most of species in my list are morpho-species.
> 
> **raw_backbone:** [raw_fernandez_backbone.txt](https://github.com/user-attachments/files/17362259/raw_fernandez_backbone.txt)
> 
> **user-modified_backbone:** [fernandez_backbone.txt](https://github.com/user-attachments/files/17362217/fernandez_backbone.txt)
> 
> **sp.list:** [test.csv](https://github.com/user-attachments/files/17361308/test.csv)
> 
> ## Code to create user-modified_backbone
> ```
> # Function 1:
> new_tip_tbl <- function(tree) {
>   tree |>
>     as_tibble() |>
>     filter(label != "NA" & label != "") |>
>     mutate(
>       new_label = str_replace_all(label, "_", " "),
>       new_label = str_remove_all(new_label, " cf"),
>       Family_v0 = case_when(
>         str_detect(new_label, "dae") ~ str_extract(new_label, "[^ ]+"),
>         TRUE ~ ""
>       ),
>       genus0 = word(new_label, 2),
>       col0 = case_when(!str_detect(new_label, "dae") ~ str_extract(new_label, "[^ ]+"), TRUE ~ ""),
>       col0 = str_replace_all(col0, "([A-Z])", " \\1"),
>       genus1 = word(col0, 2),
>       final_genus_v0 = case_when(
>         !is.na(genus0) ~ genus0,
>         TRUE ~ genus1),
>       new_tip = case_when(
>         str_detect(col0, " ") ~ col0,
>         TRUE ~ label
>       )) |> 
>     mutate(across(where(is.character), str_trim)) |> 
>     mutate(new_tip = str_replace_all(new_tip, " ", "_")) |> 
>     select(parent, node, branch.length, new_tip, final_genus_v0) |> 
>     separate(
>       new_tip,
>       sep = "_",
>       into = c("col1", "col2", "col3", "col4", "col5", "col6", "col7")
>     ) |> 
>     mutate_at(c("col4", "col5", "col6", "col7"), ~ str_replace_na(., "")) |> 
>     mutate(new_tip = case_when(
>       str_detect(col2, "cf") ~ paste(final_genus_v0, col4, col5, col6, col7, sep = " "),
>       is.na(col3) & !is.na(col2) ~ paste(final_genus_v0, col2))) |> 
>     mutate(col3 = case_when(!is.na(col3) ~ col3, is.na(col3) & is.na(col2) ~ "sp.xx")) |> 
>     mutate(new_tip = case_when(
>       !is.na(new_tip) ~ new_tip,
>       is.na(final_genus_v0) ~ paste(col1, col3, sep = " "),
>       TRUE ~ paste(final_genus_v0, col3, col4, col5, col6, col7, sep = " "))) |> 
>     mutate(across(where(is.character), str_trim)) |>
>     mutate(new_tip = str_replace_all(new_tip, " ", "_"))  
> }
> 
> # Function 2
> spider_label_update <- function(tree) {
>   tree |>
>     as_tibble() |>
>     left_join(new_tip_tbl(tree), join_by("parent", "node", "branch.length")) |>
>     mutate(label = coalesce(new_tip, label)) |> 
>     mutate(label = str_replace(label, "\\?", "")) |> 
>     select(parent, node, branch.length, label) |>
>     as.phylo()
> }
> user_modified_backbone <- spider_label_update(raw_backbone)
> ```
> 
> ### Run Phylo.maker
> ```
> gen.list <- sp.list |> 
>   distinct(genus, family)
> 
> result <- phylo.maker(sp.list, backbone, gen.list, nodes.type = 1, scenario = 3)
> ```
> 
> I got this messages:
> 
> ```
> [1] "Note: 15 species fail to be binded to the tree."
>  [1] "Alistra_sp.01"           "Hygropoda_sp.01"         "Micromerys_sp.01"        "Thaumasia_sp.01"         "Hygropoda_sp.02"         "Oedignatha_scrobiculata"
>  [7] "Ablemma_sp.01"           "Anapistula_sp.01"        "Brignoliella_sp.01"      "Crassignatha_sp.01"      "Nasoona_sp.01"           "Ablemma_sp.02"          
> [13] "Ablemma_sp.03"           "Ablemma_singalang"       "Nescina_sp.01"          
> Warning messages:
> 1: Setting row names on a tibble is deprecated. 
> 2: Setting row names on a tibble is deprecated. 
> 3: Setting row names on a tibble is deprecated. 
> ```
> 
> These morpho species - their genera are not included in the backbone, but I think that would not be the problem. I am wondering whether I do need to provide a node info table.
> 
> Thank you so much for supporting! Best, Anh

Hi Anh,

I checked your backbone phylogeny, and I found that the genera of the 15 not-binded species were not present on the backbone tree, which would result in them not in the genus list, based on your R codes, I guess. To improve the chance of successfully binding the species in your list to the backbone tree, you need to make sure every genus in your species list is present in the genus list. If a genus in your list is not in the genus list, you can add it by hand. After this is done, you run the phylo.maker function again, if still there is species missing on the tree, it then imply that the family of the missing species is not in the backbone phylogeny, and you may need a backbone phylogeny that includes all the families of your species list.

Best,

Yi

**Comment by duc-anhle** [comment]
Thank you so much for answering me! It helped me!
